# Generated by Django 4.2.5 on 2023-09-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='Agency',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
