# Generated by Django 4.2.5 on 2023-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0005_coolingforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingforecast',
            name='Design_cooling',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coolingforecast',
            name='Diff_Outlet_Wetbulb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
