# Generated by Django 4.2.5 on 2023-10-04 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0007_coolingforecast_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingforecast',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
