# Generated by Django 4.2.5 on 2023-10-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0010_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
