# Generated by Django 4.2.5 on 2023-10-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0014_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coolingforecast',
            old_name='Design_cooling',
            new_name='Approach_Temperature',
        ),
        migrations.RenameField(
            model_name='coolingforecast',
            old_name='Diff_Outlet_Wetbulb',
            new_name='Delta_T',
        ),
    ]
