# Generated by Django 4.2.5 on 2023-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingapp', '0017_cookieconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
